(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas?.getContext('2d'),quick=$('quick-match-btn'),cancel=$('cancel-match-btn'),fallback=$('match-ai-fallback-btn'),menu=$('menu'),match=$('match-screen'),status=$('match-status'),qtime=$('queue-time'),qonline=$('queue-online'),countdown=$('countdown'),ctext=$('countdown-text'),hud=$('hud'),aScore=$('ai-score'),pScore=$('player-score'),speed=$('speed-label'),combo=$('combo-label'),best=$('best-combo-hud'),streak=$('win-streak-hud'),pause=$('pause-btn'),over=$('game-over'),winner=$('winner-text'),final=$('final-score'),restart=$('restart-button'),home=$('home-button');
if(!canvas||!ctx||!quick)return;
const cfg=window.BUBBLE_CLOUD_CONFIG||{},ok=!!(cfg.enabled&&cfg.supabaseUrl&&cfg.supabasePublishableKey&&window.supabase?.createClient),sb=ok?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false},realtime:{params:{eventsPerSecond:40}}}):null;
const W={w:1000,h:1600,l:45,r:955,t:150,b:1550,m:850,gl:315,gr:685,pr:76,br:30},clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
let user,name='玩家',role,opp='對手',mid,ch,mode='idle',qs=0,qt=0,pt=0,ct=0,ht=0,raf=0,last=0,lastState=0,lastInput=0,lastRemote=0,lastReady=0,guestReady=false,started=false,pointer=null,pingAt=0,latency=0,ended=false,snap=null;
const me={x:500,y:1430,tx:500,ty:1430},them={x:500,y:270,tx:500,ty:270},ball={x:500,y:850,vx:140,vy:-520},game={hs:0,gs:0,pause:0,dir:-1,seq:0},disp={x:500,y:850,ox:500,oy:270};
const readName=()=>{try{name=String(JSON.parse(localStorage.getItem('bubble_island_user')||'{}').name||'玩家').trim().slice(0,12)||'玩家'}catch{name='玩家'}};
async function auth(){if(!sb)throw Error('NO_CLOUD');const {data:{session}}=await sb.auth.getSession();if(session?.user){user=session.user;return}const {data,error}=await sb.auth.signInAnonymously({options:{data:{player_name:name}}});if(error)throw error;user=data.user}
const msg=t=>{if(status)status.textContent=t},fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function clearQueue(){clearInterval(qt);clearInterval(pt);clearInterval(ct);qt=pt=ct=0}
function showQueue(){menu?.classList.remove('active');over?.classList.remove('active');match?.classList.add('active');if(fallback)fallback.hidden=true;qs=0;if(qtime)qtime.textContent='00:00';if(qonline)qonline.textContent='等待玩家：計算中'}
function showMenu(){match?.classList.remove('active');over?.classList.remove('active');countdown?.classList.remove('active');menu?.classList.add('active')}
function onlineHud(){document.body.classList.add('multiplayer-running');hud?.classList.add('multiplayer-hud');if(combo)combo.textContent='真人對戰';if(best)best.textContent='即時連線';if(streak)streak.textContent=role==='host'?'主場':'客場';if(pause){pause.textContent='✕';pause.setAttribute('aria-label','離開真人對戰')}scoreHud()}
function resetHud(){document.body.classList.remove('multiplayer-running');hud?.classList.remove('multiplayer-hud');if(pause){pause.textContent='Ⅱ';pause.setAttribute('aria-label','暫停')}}
function scoreHud(){const m=role==='host'?game.hs:game.gs,o=role==='host'?game.gs:game.hs;if(pScore)pScore.textContent=`${name} ${m}`;if(aScore)aScore.textContent=`${opp} ${o}`;if(speed)speed.textContent=latency?`ONLINE ${latency}ms`:'ONLINE'}
async function waitingCount(){if(!sb||mode!=='queue')return;const {data}=await sb.rpc('quick_match_waiting_count');if(qonline&&Number.isFinite(data))qonline.textContent=`等待玩家：${data}`}
async function startQueue(){if(mode!=='idle'&&mode!=='finished')return;readName();mode='queue';ended=false;showQueue();msg('正在建立安全連線…');try{await auth()}catch(e){mode='idle';msg(e.message==='NO_CLOUD'?'雲端設定尚未完成。':'匿名連線失敗，請重新整理再試。');return}msg('正在尋找真人對手…');qt=setInterval(()=>{qs++;if(qtime)qtime.textContent=fmt(qs);if(qs===10)msg('目前配對人數較少，繼續等待中…');if(qs>=30&&fallback)fallback.hidden=false},1000);await poll();pt=setInterval(poll,1250);ct=setInterval(waitingCount,4000);waitingCount()}
async function poll(){if(mode!=='queue'||!sb)return;const {data,error}=await sb.rpc('join_quick_match',{p_player_name:name});if(error){console.error(error);msg(error.code==='PGRST202'||String(error.message).includes('join_quick_match')?'多人資料庫尚未安裝，請先執行 multiplayer-matchmaking.sql':'配對服務暫時無法連線，正在重試…');return}const row=Array.isArray(data)?data[0]:data;if(row?.match_id){role=row.player_role;opp=row.opponent_name||'對手';mid=row.match_id;clearQueue();msg(`找到對手：${opp}`);connect()}}
async function connect(){mode='connecting';msg(`正在連接 ${opp}…`);await sb.realtime.setAuth();ch=sb.channel(`game:${mid}:play`,{config:{private:true,broadcast:{ack:false,self:false}}});ch.on('broadcast',{event:'ready'},({payload})=>{lastRemote=performance.now();if(role==='host'&&payload?.role==='guest'){guestReady=true;hostStart()}if(role==='guest'&&payload?.role==='host')ready()}).on('broadcast',{event:'start'},({payload})=>{lastRemote=performance.now();if(role==='guest'&&!['playing','countdown'].includes(mode))begin(payload?.seed||Date.now())}).on('broadcast',{event:'input'},({payload})=>{if(role!=='host'||!payload)return;lastRemote=performance.now();them.tx=clamp(+payload.x||500,W.l+W.pr,W.r-W.pr);them.ty=clamp(+payload.y||270,W.t+W.pr,W.m-W.pr-12)}).on('broadcast',{event:'state'},({payload})=>{if(role!=='guest'||!payload)return;lastRemote=performance.now();snap=payload;game.hs=payload.hs||0;game.gs=payload.gs||0;scoreHud();if(payload.ended)finish(payload.winner,'remote')}).on('broadcast',{event:'ping'},({payload})=>{lastRemote=performance.now();send('pong',{t:payload?.t||Date.now()})}).on('broadcast',{event:'pong'},({payload})=>{lastRemote=performance.now();latency=Math.max(1,Math.round((Date.now()-(payload?.t||Date.now()))/2));scoreHud()}).on('broadcast',{event:'leave'},()=>finish(role,'opponent-left')).subscribe(s=>{if(s==='SUBSCRIBED'){lastRemote=performance.now();ready();msg(`已連上 ${opp}，等待同步…`);clearInterval(ht);ht=setInterval(()=>{if(mode!=='connecting'){clearInterval(ht);return}ready()},1400);hostStart()}else if(s==='CHANNEL_ERROR'||s==='TIMED_OUT')msg('即時連線失敗，正在重新連線…')})}
const send=(event,payload)=>ch?ch.send({type:'broadcast',event,payload}):Promise.resolve(),ready=()=>{lastReady=performance.now();send('ready',{role,name})};
function hostStart(){if(role!=='host'||!guestReady||started||!ch)return;started=true;Promise.resolve(sb.rpc('start_quick_match',{p_match_id:mid})).catch(()=>{});const seed=Date.now();send('start',{seed});begin(seed)}
async function begin(seed){if(['countdown','playing'].includes(mode))return;mode='countdown';clearInterval(ht);match?.classList.remove('active');onlineHud();reset(seed);countdown?.classList.add('active');for(const v of ['3','2','1','GO']){if(mode!=='countdown')return;if(ctext)ctext.textContent=v;await new Promise(r=>setTimeout(r,v==='GO'?260:420))}countdown?.classList.remove('active');mode='playing';last=performance.now();lastRemote=performance.now();raf=requestAnimationFrame(loop)}
function reset(seed){game.hs=0;game.gs=0;game.pause=.35;game.dir=seed%2?1:-1;game.seq=0;Object.assign(me,{x:500,y:1430,tx:500,ty:1430});Object.assign(them,{x:500,y:270,tx:500,ty:270});Object.assign(ball,{x:500,y:850,vx:(seed%401)-200,vy:game.dir*520});snap=null;Object.assign(disp,{x:500,y:850,ox:500,oy:270});scoreHud()}
function move(o,x,y,max,dt){const dx=x-o.x,dy=y-o.y,d=Math.hypot(dx,dy);if(!d)return;const s=Math.min(d,max*dt);o.x+=dx/d*s;o.y+=dy/d*s}
function hit(p){const dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy),min=W.br+W.pr*.9;if(!d||d>=min)return;const nx=dx/d,ny=dy/d;ball.x=p.x+nx*min;ball.y=p.y+ny*min;const dot=ball.vx*nx+ball.vy*ny;if(dot<0){ball.vx-=1.88*dot*nx;ball.vy-=1.88*dot*ny}const s=Math.hypot(ball.vx,ball.vy);if(s>1180){ball.vx*=1180/s;ball.vy*=1180/s}}
function serve(d){Object.assign(ball,{x:500,y:850,vx:(Math.random()-.5)*240,vy:d*520});game.pause=.85;game.dir=d}
function sim(dt){move(me,me.tx,me.ty,1700,dt);move(them,them.tx,them.ty,1700,dt);me.x=clamp(me.x,W.l+W.pr,W.r-W.pr);me.y=clamp(me.y,W.m+W.pr+12,W.b-W.pr);them.x=clamp(them.x,W.l+W.pr,W.r-W.pr);them.y=clamp(them.y,W.t+W.pr,W.m-W.pr-12);if(game.pause>0){game.pause-=dt;return}const s=Math.hypot(ball.vx,ball.vy),steps=clamp(Math.ceil(s*dt/14),1,8),step=dt/steps;for(let i=0;i<steps;i++){ball.x+=ball.vx*step;ball.y+=ball.vy*step;if(ball.x-W.br<W.l){ball.x=W.l+W.br;ball.vx=Math.abs(ball.vx)}if(ball.x+W.br>W.r){ball.x=W.r-W.br;ball.vx=-Math.abs(ball.vx)}const goal=ball.x>W.gl+W.br*.25&&ball.x<W.gr-W.br*.25;if(ball.y-W.br<W.t){if(goal&&ball.y+W.br<W.t-5){game.hs++;serve(-1);break}if(!goal){ball.y=W.t+W.br;ball.vy=Math.abs(ball.vy)}}if(ball.y+W.br>W.b){if(goal&&ball.y-W.br>W.b+5){game.gs++;serve(1);break}if(!goal){ball.y=W.b-W.br;ball.vy=-Math.abs(ball.vy)}}hit(me);hit(them)}ball.vx*=Math.pow(.9982,dt*60);ball.vy*=Math.pow(.9982,dt*60);const z=Math.hypot(ball.vx,ball.vy);if(z<300&&game.pause<=0){ball.vx*=300/Math.max(1,z);ball.vy*=300/Math.max(1,z)}if(Math.abs(ball.vy)<100)ball.vy=(ball.vy<0?-1:1)*100;if(game.hs>=7||game.gs>=7){const w=game.hs>game.gs?'host':'guest';state(true,w);Promise.resolve(sb.rpc('finish_quick_match',{p_match_id:mid,p_host_score:game.hs,p_guest_score:game.gs})).catch(()=>{});finish(w,'score')}}
function state(done=false,winner=null){game.seq++;send('state',{seq:game.seq,px:ball.x,py:ball.y,hx:me.x,hy:me.y,gx:them.x,gy:them.y,hs:game.hs,gs:game.gs,ended:done,winner})}
function guest(dt){if(snap){const t=1-Math.pow(.08,dt*60);disp.x=lerp(disp.x,W.w-snap.px,t);disp.y=lerp(disp.y,W.h-snap.py,t);disp.ox=lerp(disp.ox,W.w-snap.hx,t);disp.oy=lerp(disp.oy,W.h-snap.hy,t)}move(me,me.tx,me.ty,1700,dt);me.x=clamp(me.x,W.l+W.pr,W.r-W.pr);me.y=clamp(me.y,W.m+W.pr+12,W.b-W.pr)}
function loop(now){if(mode!=='playing')return;const dt=Math.min(.034,(now-last)/1000||.016);last=now;if(role==='host'){sim(dt);if(now-lastState>=40){lastState=now;state()}}else{guest(dt);if(now-lastInput>=34){lastInput=now;send('input',{x:W.w-me.x,y:W.h-me.y})}}if(now-pingAt>2200){pingAt=now;send('ping',{t:Date.now()})}if(now-lastReady>2500&&now-lastRemote>1800)ready();if(lastRemote&&now-lastRemote>9000){finish(role,'timeout');return}draw();raf=requestAnimationFrame(loop)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W.w,y:(e.clientY-r.top)/r.height*W.h}}
canvas.addEventListener('pointerdown',e=>{if(mode!=='playing'||pointer!==null)return;const p=point(e);if(p.y<W.m-30)return;pointer=e.pointerId;canvas.setPointerCapture?.(e.pointerId);me.tx=p.x;me.ty=p.y-55},{passive:true});canvas.addEventListener('pointermove',e=>{if(mode!=='playing'||pointer!==e.pointerId)return;const a=e.getCoalescedEvents?.()||[e],p=point(a[a.length-1]);me.tx=p.x;me.ty=p.y-55},{passive:true});const release=e=>{if(pointer===e.pointerId)pointer=null};canvas.addEventListener('pointerup',release,{passive:true});canvas.addEventListener('pointercancel',release,{passive:true});
const sc=(x,y)=>({x:x/W.w*innerWidth,y:y/W.h*innerHeight}),rr=r=>r*Math.min(innerWidth/W.w,innerHeight/W.h);
function shell(x,y,r,t){const p=sc(x,y),s=rr(r);ctx.save();ctx.translate(p.x,p.y);const g=ctx.createRadialGradient(-s*.28,-s*.3,2,0,0,s);if(t==='t'){g.addColorStop(0,'#eaf7b5');g.addColorStop(.45,'#60c795');g.addColorStop(1,'#34785f')}else{g.addColorStop(0,'#fff1cc');g.addColorStop(.46,'#f6ab83');g.addColorStop(1,'#c96c69')}ctx.fillStyle=g;ctx.strokeStyle='#36586b';ctx.lineWidth=Math.max(3,s*.09);ctx.beginPath();ctx.ellipse(0,0,s*.98,s*.84,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='rgba(54,88,107,.55)';ctx.lineWidth=Math.max(2,s*.055);if(t==='t'){ctx.beginPath();ctx.moveTo(-s*.5,-s*.34);ctx.lineTo(0,s*.38);ctx.lineTo(s*.5,-s*.34);ctx.moveTo(-s*.22,-s*.05);ctx.lineTo(0,-s*.45);ctx.lineTo(s*.22,-s*.05);ctx.stroke()}else{ctx.beginPath();for(let a=0;a<Math.PI*5.2;a+=.15){const q=s*(.06+a/(Math.PI*5.2)*.58),x=Math.cos(a)*q,y=Math.sin(a)*q*.84;a?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}ctx.restore()}
function draw(){const g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,'#86dcf4');g.addColorStop(1,'#e4fbff');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);const tl=sc(W.l,W.t),br=sc(W.r,W.b);ctx.fillStyle='rgba(74,190,170,.35)';ctx.strokeStyle='#36586b';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect?ctx.roundRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y,30):ctx.rect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);ctx.fill();ctx.stroke();const y=sc(0,W.m).y;ctx.strokeStyle='rgba(255,255,255,.85)';ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(tl.x+15,y);ctx.lineTo(br.x-15,y);ctx.stroke();ctx.setLineDash([]);const gt=sc(W.gl,W.t),gr=sc(W.gr,W.t),gb=sc(W.gl,W.b);ctx.lineWidth=12;ctx.strokeStyle='#f19778';ctx.beginPath();ctx.moveTo(gt.x,gt.y);ctx.lineTo(gr.x,gr.y);ctx.stroke();ctx.strokeStyle='#5bc696';ctx.beginPath();ctx.moveTo(gb.x,gb.y);ctx.lineTo(sc(W.gr,W.b).x,gb.y);ctx.stroke();let bx,by,ox,oy;if(role==='host'){bx=ball.x;by=ball.y;ox=them.x;oy=them.y}else{bx=disp.x;by=disp.y;ox=disp.ox;oy=disp.oy}const bp=sc(bx,by),r=rr(W.br);ctx.fillStyle='#fff5bd';ctx.strokeStyle='#36586b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(bp.x,bp.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();shell(ox,oy,W.pr,'s');shell(me.x,me.y,W.pr,'t')}
async function finish(w,reason){if(ended)return;ended=true;clearInterval(ht);if((reason==='timeout'||reason==='opponent-left')&&sb)Promise.resolve(sb.rpc('cancel_quick_match')).catch(()=>{});cancelAnimationFrame(raf);mode='finished';pointer=null;const won=w===role;if(winner)winner.textContent=reason==='opponent-left'||reason==='timeout'?'對手已離線':won?'真人對戰勝利！':'真人對戰結束';const ms=role==='host'?game.hs:game.gs,os=role==='host'?game.gs:game.hs;if(final)final.textContent=`${name} ${ms}：${os} ${opp}${reason==='timeout'?'｜連線逾時':''}`;if(restart)restart.textContent='🌐 再次配對';if(home)home.textContent='⌂ 回主選單';over?.classList.add('active');resetHud()}
async function leave(reason='user'){const active=['queue','connecting','countdown','playing'].includes(mode);if(active&&ch)send('leave',{reason});clearQueue();clearInterval(ht);cancelAnimationFrame(raf);if(sb&&active)Promise.resolve(sb.rpc('cancel_quick_match')).catch(()=>{});if(ch&&sb){await sb.removeChannel(ch).catch(()=>{});ch=null}mode='idle';role=mid=null;guestReady=started=ended=false;pointer=null;resetHud();showMenu()}
quick.addEventListener('click',e=>{e.preventDefault();startQueue()});cancel?.addEventListener('click',e=>{e.preventDefault();leave('cancel')});fallback?.addEventListener('click',async e=>{e.preventDefault();await leave('ai');$('start-button')?.click()});pause?.addEventListener('click',e=>{if(['connecting','countdown','playing'].includes(mode)){e.preventDefault();e.stopImmediatePropagation();leave('exit')}},true);restart?.addEventListener('click',e=>{if(mode==='finished'){e.preventDefault();e.stopImmediatePropagation();over?.classList.remove('active');mode='idle';startQueue()}},true);home?.addEventListener('click',e=>{if(mode==='finished'){e.preventDefault();e.stopImmediatePropagation();leave('home')}},true);window.BubbleMultiplayer={start:startQueue,leave,isActive:()=>mode!=='idle'};if(!ok){quick.disabled=true;quick.textContent='🌐 雲端尚未連線'}
})();